### ISSUE TITLE
Number of replies should include sub-replies

### ISSUE THREAD

**Issue by stellarmagnet** [spacedecentral/spacedecentral-network#16]
Right now the reply count is only for first level replies.

The count should be the total of all replies to the thread, regardless of it's comment level

**Comment by ottodevs** [comment]
Should we take in account all replies in the thread for the trending filter? (it currently minds only about first level replies also, for the sorting criteria), so it could be confusing for the user sort by trending/replies and see post with more 1st level replies count below posts with less 1st level replies but more replies in total, I hope you understand what I mean 👍
