### ISSUE TITLE
Load more link in forum isn't loading more

### ISSUE THREAD

**Issue by stellarmagnet** [spacedecentral/spacedecentral-network#2]
Go to the forum, scroll down, click "Load More" link. It is not loading any additional forum posts.

https://spacedecentral.net/forum

This may also effect the mission/project forums

**Comment by rkzel** [comment]
Actually it does load additional posts, but in a non-obvious way. You have to scroll up and down to see the difference after clicking "load more". Which means it needs to be replaced with "infinite scroll" which loads posts below what's already visible.
