### ISSUE TITLE
Forum threads with new replies should be at the top of the page

### ISSUE THREAD

**Issue by stellarmagnet** [spacedecentral/spacedecentral-network#29]
It seems like forum threads are being sorted based on the posting date of the original thread, and not based on the date of the last reply in the thread.

Fix: We should sort forum threads by the date of the last reply in that thread.

Note: Pinned threads should always be at the top.

**Comment by topocount** [comment]
Instead of trimming extra levels of the comments, it would be better (no information loss) to replace indentations beyond 3 levels with dots, like reddit's mobile frontend in their comments.

**Comment by stellarmagnet** [comment]
@topocount I think that comment was meant for #28 ?
