### ISSUE TITLE
Forum post URLs are missing the hash

### ISSUE THREAD

**Issue by stellarmagnet** [spacedecentral/spacedecentral-network#31]
There used to be a hash at the end of a forum post name, but now that no longer occurs. This can cause problems if we get some forum posts with the same name. Seems there was some regression

Example:
* https://spacedecentral.net/forum/posts/book-club

vs an older one:

* https://spacedecentral.net/forum/posts/building-design-outline-7059fce6

**Comment by ottodevs** [comment]
Hi Yalda! I was testing the platform with the purpose of fixing some of the issues, this one specifically does not seem an issue for me, since when you create a post with the same name it actually adds the hash at the end to keep duplicate title posts with separate URLs, ruby on rails is very smart in fact!!
Try it if you don't believe 👍 

I think you can safely close this issue :)

**Comment by ottodevs** [comment]
Probably in the example there existed an older version with the same title (building design outline) that is the reason the hash was automatically added at the end.

**Comment by ottodevs** [comment]
If you decide that is better to have hashes at the end of every post title, then we could change slug_candidates in models/post.rb to force this behaviour

**Comment by stellarmagnet** [comment]
@ottodevs nice catch :) thanks for looking into this! 

Do you think every post should have the hash for consistency? I guess i'm not sure what is standard web behavior for this design pattern

**Comment by ottodevs** [comment]
Well I don't really know what to say about that, I think is a matter of taste, I really like the simplicity of having pure text slugs with the fallback of the hash for duplicated titles, some forum platforms like thredded, seem to have the same behavior, but others like discourse or lithium have a consistent numeric slug apart from the text for every forum topic, so, I think there is not a standard on this 😅 

If it helps, for this case I would recall the good ol' programmer rule: "If It Is Working Don't Change"
