### ISSUE TITLE
Issues with uploading profile images - getting imagemagick errors on production

### ISSUE THREAD

**Issue by stellarmagnet** [spacedecentral/spacedecentral-network#39]
when some users update their profiles, this error is thrown to our server:

Could not run the `identify` command. Please install ImageMagick.
app/controllers/users_controller.rb:94:in `update_personal'

**Comment by rkzel** [comment]
I've installed IM and 'identify' command is now available.

**Comment by rkzel** [comment]
...although it solved the problem only partially - there is no front-end error, but photos are not saved. Investigating.

**Comment by rkzel** [comment]
AWS key adjusted, uploads work now.
